version: '3.4'

services:
  unify.api:
    image: ${DOCKER_REGISTRY-}unify.api
    container_name: Unify.Api
    user: root
    build:
      context: .
      dockerfile: src/Unify.Api/Dockerfile
    volumes:
      - C:/Users/jakub/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    depends_on:
      - unify-db
    ports:
      - 5001:443


  unify-db:
    image: postgres:latest
    container_name: Unify.Db
    environment:
      - POSTGRES_DB=unify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5433:5432

  unify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Unify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/unify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080
